### ISSUE TITLE
No module named confusable_homoglyphs

### ISSUE THREAD

**Issue by kwill** [ubernostrum/django-registration#115]
After updating to django-registration 2.3 and starting my site I get the following error:

	Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fd80e0ad158>
	Traceback (most recent call last):
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/django/utils/autoreload.py", line 228, in wrapper
	    fn(*args, **kwargs)
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
	    self.check(display_num_errors=True)
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
	    include_deployment_checks=include_deployment_checks,
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
	    return checks.run_checks(**kwargs)
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
	    new_errors = check(app_configs=app_configs)
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/checks/urls.py", line 16, in check_url_config
	    return check_resolver(resolver)
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
	    return check_method()
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/django/urls/resolvers.py", line 254, in check
	    for pattern in self.url_patterns:
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
	    res = instance.__dict__[self.name] = self.func(instance)
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
	    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
	    res = instance.__dict__[self.name] = self.func(instance)
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
	    return import_module(self.urlconf_name)
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/importlib/__init__.py", line 126, in import_module
	    return _bootstrap._gcd_import(name[level:], package, level)
	  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
	  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
	  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
	  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
	  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
	  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
	  File "/home/user/Documents/django_site/settings/urls.py", line 19, in <module>
	    from registration.backends.simple.views import RegistrationView
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/registration/backends/simple/views.py", line 10, in <module>
	    from registration.views import RegistrationView as BaseRegistrationView
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/registration/views.py", line 12, in <module>
	    from registration.forms import RegistrationForm
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/registration/forms.py", line 19, in <module>
	    from . import validators
	  File "/home/user/.virtualenvs/django_env/lib/python3.5/site-packages/registration/validators.py", line 10, in <module>
	    from confusable_homoglyphs import confusables
	ImportError: No module named 'confusable_homoglyphs'

Also reported in the following locations (with notes on workarounds):
* https://stackoverflow.com/questions/46512148
* https://github.com/vhf/confusable_homoglyphs/issues/5

**Comment by kwill** [comment]
My bad, this was a configuration error (I didn't update my virtualenv).
