### ISSUE TITLE
Use confusable-homoglyphs 3.0 not 2.x as it fixes problems with datafiles

### ISSUE THREAD

**Issue by simonwagner** [ubernostrum/django-registration#120]
With django-registration I am currently running into the following problem:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/pomlic/pomlic/urls.py", line 13, in <module>
    import registration.backends.hmac.urls
  File "/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/urls.py", line 10, in <module>
    from . import views
  File "/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/views.py", line 15, in <module>
    from registration.views import ActivationView as BaseActivationView
  File "/usr/local/lib/python2.7/dist-packages/registration/views.py", line 12, in <module>
    from registration.forms import RegistrationForm
  File "/usr/local/lib/python2.7/dist-packages/registration/forms.py", line 19, in <module>
    from . import validators
  File "/usr/local/lib/python2.7/dist-packages/registration/validators.py", line 10, in <module>
    from confusable_homoglyphs import confusables
  File "/usr/local/lib/python2.7/dist-packages/confusable_homoglyphs/confusables.py", line 7, in <module>
    from .categories import unique_aliases, alias
  File "/usr/local/lib/python2.7/dist-packages/confusable_homoglyphs/categories.py", line 147, in <module>
    raise Exception('Datafile not found, datafile generation failed!')
Exception: Datafile not found, datafile generation failed!
```

This is caused by `confusable-homoglyphs` trying to download certain files into the current working directory, which is not possible in my case. See also https://stackoverflow.com/questions/46512148/datafile-not-found-datafile-generation-failed-in-confusable-homoglyphs-categori

The author of `confusable-homoglyphs` claims to have fixed this problem in 3.0.0 by including a static version of those file in his package. Could you change your requirement of `confusable-homoglyphs` to 3.0.0? You also seem to have run into this problem according to commit https://github.com/ubernostrum/django-registration/commit/8904da98eeecfe5d814f58638ad6aed130ebc093

**Comment by ubernostrum** [comment]
There's [a PR already open for this](https://github.com/ubernostrum/django-registration/pull/119), I just haven't yet had a chance to review, as I just got back from a conference and have a bit of a cold.

**Comment by simonwagner** [comment]
Thanks, get well soon.
