### ISSUE TITLE
AssertionError: Actual template(s) used: useregistration/email/subject.txt, useregistration/email/body.txt

### ISSUE THREAD

**Issue by seospace** [ubernostrum/django-registration#145]
````
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..<HttpResponseRedirect status_code=302, "text/html; charset=utf-8", url="/konto/rejestracja/sukces/">
F
======================================================================
FAIL: test_registration (useregistration.tests.test_views.MyRegistrationViewTestCase)
test if registration workflow works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\...\useregistration\tests\test_views.py", line 58, in test_registration
    self.assertTemplateUsed(resp, self.TEMPLATE_NAME)
  File "C:\Users\...\lib\site-packages\django\test\testcases.py", line 559, in assertTemplateUsed
    % (template_name, ', '.join(template_names))
AssertionError: False is not true : Template 'useregistration/registration_form.html' was not a template used to render the response. Actual template(s) used: useregistration/email/subject.txt, useregistration/email/body.txt

----------------------------------------------------------------------
Ran 3 tests in 1.015s

FAILED (failures=1)
Destroying test database for alias 'default'...

````
Structure:
![2018-03-24_14-08-01](https://user-images.githubusercontent.com/35610968/37864314-eb480974-2f6c-11e8-9b43-04bac2059c86.png)

Here is my code:
https://gist.github.com/seospace/8a47fa672ebf5228aed2974d131b2a9b
Here is where it fails:
https://gist.github.com/seospace/8a47fa672ebf5228aed2974d131b2a9b#file-tests-py-L58
And print(resp) says:
````
..<HttpResponseRedirect status_code=302, "text/html; charset=utf-8", url="/konto/rejestracja/sukces/">
````
print(resp.__dict__):
````
{'_headers': {'content-type': ('Content-Type', 'text/html; charset=utf-8'), 'location': ('Location', '/konto/rejestracja/sukces/'), 'x-frame-options': ('X-Frame-Options', 'SAMEORIGIN'), 'content-length': ('Content-Length', '0')},
 '_closable_objects': [<WSGIRequest: POST '/konto/rejestracja/'>], '_handler_class': None, 'cookies': <SimpleCookie: >, 'closed': True, '_reason_phrase': None, '_charset': None, '_container': [b''], 'wsgi_request': <WSGIRequest:
POST '/konto/rejestracja/'>, 'client': <django.test.client.Client object at 0x000002A9FA03B320>, 'request': {'PATH_INFO': '/konto/rejestracja/', 'REQUEST_METHOD': 'POST', 'SERVER_PORT': '80', 'wsgi.url_scheme': 'http', 'CONTENT_L
ENGTH': 273, 'CONTENT_TYPE': 'multipart/form-data; boundary=BoUnDaRyStRiNg', 'wsgi.input': <django.test.client.FakePayload object at 0x000002A9FA1192E8>, 'QUERY_STRING': ''}, 'templates': [<django.template.base.Template object at
 0x000002A9FA119EB8>, <django.template.base.Template object at 0x000002A9FA128198>], 'context': [[{'True': True, 'False': False, 'None': None}, {'scheme': 'https', 'activation_key': 'InB5dGhvbmNvbnRyb2xAZ21haWwuY29tIg:1eziwR:qEl0
zcQFeqqRD9asOCh54QOs1hk', 'expiration_days': 1, 'site': <django.contrib.sites.requests.RequestSite object at 0x000002A9FA119C18>, 'user': <User: good_email@o2.pl>}], [{'True': True, 'False': False, 'None': None}, {'scheme'
: 'https', 'activation_key': 'InB5dGhvbmNvbnRyb2xAZ21haWwuY29tIg:1eziwR:qEl0zcQFeqqRD9asOCh54QOs1hk', 'expiration_days': 1, 'site': <django.contrib.sites.requests.RequestSite object at 0x000002A9FA119C18>, 'user': <User: good_email@o2.pl>}]], 'json': functools.partial(<bound method Client._parse_json of <django.test.client.Client object at 0x000002A9FA03B320>>, <HttpResponseRedirect status_code=302, "text/html; charset=utf-8", url="/konto/rejestra
cja/sukces/">), 'resolver_match': <SimpleLazyObject: <function Client.request.<locals>.<lambda> at 0x000002A9FA11E0D0>>}
````
````
        for tem in resp.__dict__['templates']:
            print(tem.name)
````
````
useregistration/email/subject.txt
useregistration/email/body.txt

````

**Comment by seospace** [comment]
Here is small repo that demonstrates that with fresh django, is that desired behaviour?
https://github.com/seospace/djangorendertostringtest
