### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by Ya2s** [ubernostrum/django-registration#148]
Hello,

When I try to register a new  custom user, I have this error : 

`[Errno 111] Connection refused`

In the console : 

```
...
Internal Server Error: /espace-membre/inscription/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/registration/views.py", line 33, in dispatch
    return super(RegistrationView, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/usr/local/lib/python2.7/dist-packages/registration/views.py", line 36, in form_valid
    new_user = self.register(form)
  File "/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/views.py", line 36, in register
    new_user = self.create_inactive_user(form)
  File "/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/views.py", line 55, in create_inactive_user
    self.send_activation_email(new_user)
  File "/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/views.py", line 100, in send_activation_email
    user.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 366, in email_user
    send_mail(subject, message, from_email, [self.email], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/__init__.py", line 62, in send_mail
    return mail.send()
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/message.py", line 348, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 104, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 64, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
```

My project urls : 

```
urlpatterns = [
	url(r'^admin/', admin.site.urls),
    url(r'^$', AccueilView.as_view(), name='accueil'),   
    
    url(r'^espace-membre/inscription/$', RegistrationView.as_view(form_class=InscriptionMembreForm), 
										 name='inscription',
    ),   #https://django-registration.readthedocs.io/en/2.4.1/custom-user.html : Si je met en name="registration_register" comme par "defaut", ça met une erreur (peut-être car manque des champs dans le form de base)
    url(r'^espace-membre/', include('registration.backends.hmac.urls')),
]
```

My custom user model :

```
class Membre(User):
   ...
```

And my registration form : 

```
class InscriptionMembreForm(RegistrationForm):
    class Meta:
		model = Membre
		fields = RegistrationForm.Meta.fields + ['last_name','first_name',...
```

**Why have I this error and how can I resolve it please ?**

Thank you

**Comment by Ya2s** [comment]
I resolved the problem (Thanks Google, StackOverflow, code.djangoproject.com, yahoo).
