### ISSUE TITLE
Dependency issue with confusable-homoglyphs on Python 3.4.2

### ISSUE THREAD

**Issue by Paul424** [ubernostrum/django-registration#164]
When installing django-registration==2.5.2 on a Python 3.4.2 system (in this case the aws-eb-python-dockerfiles:3.4.2-aws-eb-onbuild) an issue is raised with the dep spec.

(nenv) (app)root@f943b5ccc59d:/var/app# pip3 install django-registration==2.5.2
Downloading/unpacking django-registration==2.5.2
  Downloading django_registration-2.5.2-py2.py3-none-any.whl (117kB): 117kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/var/app/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 2482, in _dep_map
    return self.__dep_map
  File "/var/app/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 2344, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/app/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/var/app/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/var/app/lib/python3.4/site-packages/pip/req.py", line 1265, in prepare_files
    req_to_install.extras):
  File "/var/app/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/var/app/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/var/app/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 2508, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/var/app/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/var/app/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'confusable-homoglyphs ~=3.0', 'at', ' ~=3.0')

Storing debug log for failure in /root/.pip/pip.log

**Comment by Paul424** [comment]
FYI: Solve using: pip3 install --upgrade pip
