### ISSUE TITLE
django 1.8 support

### ISSUE THREAD

**Issue by auvipy** [ubernostrum/django-registration#4]

**Comment by KleeTaurus** [comment]
My django version is 1.8.1, when I execute the command `python manage.py migrate`, I got following errors:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Kevin/Devel/kushim_project/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/Kevin/Devel/kushim_project/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/Kevin/Devel/kushim_project/venv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Kevin/Devel/kushim_project/venv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Kevin/Devel/kushim_project/venv/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Kevin/Devel/kushim_project/venv/lib/python2.7/site-packages/registration/models.py", line 15, in <module>
    User = get_user_model()
  File "/Users/Kevin/Devel/kushim_project/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 150, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "/Users/Kevin/Devel/kushim_project/venv/lib/python2.7/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/Users/Kevin/Devel/kushim_project/venv/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

**Comment by ubernostrum** [comment]
The current master branch works on 1.8, and will be the basis of a new release in the near future.

**Comment by sergafts** [comment]
This issue applies to Django 1.7.7 in my case ( Django 1.8 works for me).

I am unsure though if django-registration is compatible with Django 1.7. Docs say versions 2.0.x are, but I am getting the same error message. I can see other users have this exact issue too.

If it is indeed compatible, can you provide a workaround or a hint to what we might be missing?

**Comment by ubernostrum** [comment]
2.0.4 [passes on Django 1.7](https://travis-ci.org/ubernostrum/django-registration/builds/101340602), so if for some reason you're still using Django 1.7 you should be able to use 2.0.4 on it.

Current master branch is prepping for 2.1, which will not support Django 1.7.
