### ISSUE TITLE
registration complete failing with registration.backends.hmac.urls and namespace argument

### ISSUE THREAD

**Issue by bdauer** [ubernostrum/django-registration#75]
Hello,

Initially I provided a `namespace=registration` argument in my `urls.py` with the include of `registration.backends.hmac.urls`. 

I received the following traceback:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/registration/views.py", line 33, in dispatch
    return super(RegistrationView, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/usr/local/lib/python3.6/site-packages/registration/views.py", line 44, in form_valid
    return redirect(to, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py", line 56, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py", line 147, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 392, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'registration_complete' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []`

However when I removed the namespace argument it worked as expected. Not sure if this is a bug or I did something wrong in this case.

**Comment by ubernostrum** [comment]
When you're using namespaced URLs, any calls to `reverse` or the `url` template tag should include the namespace. So you'd want to also override `get_success_url` to return `registration:registration_complete` as the URL name, instead of just `registration`.
